package CharrLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCharrItem = createDescriptorForCharrItem();
  /*package*/ final ConceptDescriptor myConceptCharrList = createDescriptorForCharrList();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCharrItem, myConceptCharrList);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.CharrItem:
        return myConceptCharrItem;
      case LanguageConceptSwitch.CharrList:
        return myConceptCharrList;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCharrItem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CharrLang", "CharrItem", 0xa9bfc4bb9246402cL, 0x89fdb26089a27f80L, 0x484f18c3b4f6cffbL);
    b.class_(false, false, false);
    b.origin("r:391e7ae7-1069-42d3-bd9d-6674be93e43e(CharrLang.structure)/5210410522724716539");
    b.version(3);
    b.property("description", 0x484f18c3b4f6d004L).type(PrimitiveTypeId.STRING).origin("5210410522724716548").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCharrList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("CharrLang", "CharrList", 0xa9bfc4bb9246402cL, 0x89fdb26089a27f80L, 0x484f18c3b4f59b1cL);
    b.class_(false, false, true);
    b.origin("r:391e7ae7-1069-42d3-bd9d-6674be93e43e(CharrLang.structure)/5210410522724637468");
    b.version(3);
    b.property("name", 0x484f18c3b4f6cffeL).type(PrimitiveTypeId.STRING).origin("5210410522724716542").done();
    b.aggregate("items", 0x484f18c3b4f6d002L).target(0xa9bfc4bb9246402cL, 0x89fdb26089a27f80L, 0x484f18c3b4f6cffbL).optional(true).ordered(true).multiple(true).origin("5210410522724716546").done();
    return b.create();
  }
}
